In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sbn

In [2]:
data = pd.read_csv(r'D:\Datasets\glass.csv')
data.head()

RI     Na    Mg    Al     Si     K    Ca   Ba   Fe  Type
0  1.52101  13.64  4.49  1.10  71.78  0.06  8.75  0.0  0.0     1
1  1.51761  13.89  3.60  1.36  72.73  0.48  7.83  0.0  0.0     1
2  1.51618  13.53  3.55  1.54  72.99  0.39  7.78  0.0  0.0     1
3  1.51766  13.21  3.69  1.29  72.61  0.57  8.22  0.0  0.0     1
4  1.51742  13.27  3.62  1.24  73.08  0.55  8.07  0.0  0.0     1

In [3]:
data.shape

(214, 10)

In [4]:
data.size

2140

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 214 entries, 0 to 213
Data columns (total 10 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   RI      214 non-null    float64
 1   Na      214 non-null    float64
 2   Mg      214 non-null    float64
 3   Al      214 non-null    float64
 4   Si      214 non-null    float64
 5   K       214 non-null    float64
 6   Ca      214 non-null    float64
 7   Ba      214 non-null    float64
 8   Fe      214 non-null    float64
 9   Type    214 non-null    int64  
dtypes: float64(9), int64(1)
memory usage: 16.8 KB


In [6]:
data.describe()

RI          Na          Mg          Al          Si           K  \
count  214.000000  214.000000  214.000000  214.000000  214.000000  214.000000   
mean     1.518365   13.407850    2.684533    1.444907   72.650935    0.497056   
std      0.003037    0.816604    1.442408    0.499270    0.774546    0.652192   
min      1.511150   10.730000    0.000000    0.290000   69.810000    0.000000   
25%      1.516522   12.907500    2.115000    1.190000   72.280000    0.122500   
50%      1.517680   13.300000    3.480000    1.360000   72.790000    0.555000   
75%      1.519157   13.825000    3.600000    1.630000   73.087500    0.610000   
max      1.533930   17.380000    4.490000    3.500000   75.410000    6.210000   

               Ca          Ba          Fe        Type  
count  214.000000  214.000000  214.000000  214.000000  
mean     8.956963    0.175047    0.057009    2.780374  
std      1.423153    0.497219    0.097439    2.103739  
min      5.430000    0.000000    0.000000    1.000000  
25%      8.240000    0.000000    0.000000    1.000000  
50%      8.600000    0.000000    0.000000    2.000000  
75%      9.172500    0.000000    0.100000    3.000000  
max     16.190000    3.150000    0.510000    7.000000

In [7]:
data['Type'] = np.where(data['Type']<3,0,1)
data['Type'].value_counts()

0    146
1     68
Name: Type, dtype: int64

In [8]:
x = data.drop('Type',axis=1)
y = data['Type']

In [9]:
from imblearn.over_sampling import SMOTE
sm = SMOTE()
x_train_res,y_train_res = sm.fit_resample(x,y)
print(x_train_res.shape, y_train_res.shape)

(292, 9) (292,)


In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_train_res,y_train_res,test_size=0.25)

In [11]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = pd.DataFrame(scaler.fit_transform(x_train),columns=x_train.columns)
x_test = pd.DataFrame(scaler.fit_transform(x_test),columns=x_test.columns)

# 1 - Logistic Regression

In [12]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
logreg.fit(x_train,y_train)

LogisticRegression()

In [13]:
y_pred = logreg.predict(x_test)

In [14]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pred))
print(metrics.confusion_matrix(y_test,y_pred))
print(metrics.classification_report(y_test,y_pred))

0.8356164383561644
[[36  1]
 [11 25]]
              precision    recall  f1-score   support

           0       0.77      0.97      0.86        37
           1       0.96      0.69      0.81        36

    accuracy                           0.84        73
   macro avg       0.86      0.83      0.83        73
weighted avg       0.86      0.84      0.83        73



In [15]:
logreg.score(x_train,y_train)

0.8447488584474886

In [16]:
from sklearn.model_selection import RandomizedSearchCV
params = {
    "penalty" : ['l1','l2','elasticnet'],
    "C" : [i for i in np.linspace(0.0001,1,1000)]
}
params

{'penalty': ['l1', 'l2', 'elasticnet'],
 'C': [0.0001,
  0.001100900900900901,
  0.0021018018018018015,
  0.0031027027027027026,
  0.004103603603603604,
  0.005104504504504504,
  0.006105405405405406,
  0.0071063063063063064,
  0.008107207207207206,
  0.009108108108108108,
  0.010109009009009007,
  0.011109909909909909,
  0.01211081081081081,
  0.01311171171171171,
  0.014112612612612612,
  0.015113513513513512,
  0.016114414414414413,
  0.017115315315315315,
  0.018116216216216216,
  0.019117117117117114,
  0.020118018018018016,
  0.021118918918918917,
  0.02211981981981982,
  0.02312072072072072,
  0.02412162162162162,
  0.02512252252252252,
  0.02612342342342342,
  0.027124324324324323,
  0.028125225225225224,
  0.029126126126126126,
  0.030127027027027024,
  0.031127927927927925,
  0.03212882882882883,
  0.03312972972972973,
  0.03413063063063063,
  0.035131531531531535,
  0.036132432432432436,
  0.03713333333333334,
  0.03813423423423423,
  0.039135135135135134,
  0.04013603603603

In [17]:
rndm_cv_logreg = RandomizedSearchCV(estimator = logreg,param_distributions=params , cv = 5,n_iter = 100 ,n_jobs=-1,verbose=True)
rndm_cv_logreg.fit(x_train , y_train)

Fitting 5 folds for each of 100 candidates, totalling 500 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    3.4s
[Parallel(n_jobs=-1)]: Done 465 tasks      | elapsed:    4.2s
[Parallel(n_jobs=-1)]: Done 500 out of 500 | elapsed:    4.2s finished


RandomizedSearchCV(cv=5, estimator=LogisticRegression(), n_iter=100, n_jobs=-1,
                   param_distributions={'C': [0.0001, 0.001100900900900901,
                                              0.0021018018018018015,
                                              0.0031027027027027026,
                                              0.004103603603603604,
                                              0.005104504504504504,
                                              0.006105405405405406,
                                              0.0071063063063063064,
                                              0.008107207207207206,
                                              0.009108108108108108,
                                              0.010109009009009007,
                                              0.011109909909909909,
                                              0.01211...
                                              0.015113513513513512,
                                    

In [18]:
a = rndm_cv_logreg.best_params_
a

{'penalty': 'l2', 'C': 0.16624954954954954}

In [19]:
lgrg = LogisticRegression(C = 0.2783504504504504 )
lgrg.fit(x_train,y_train)

LogisticRegression(C=0.2783504504504504)

In [20]:
y_pr = lgrg.predict(x_test)

In [21]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pr))
print(metrics.confusion_matrix(y_test,y_pr))
print(metrics.classification_report(y_test,y_pr))

0.8356164383561644
[[36  1]
 [11 25]]
              precision    recall  f1-score   support

           0       0.77      0.97      0.86        37
           1       0.96      0.69      0.81        36

    accuracy                           0.84        73
   macro avg       0.86      0.83      0.83        73
weighted avg       0.86      0.84      0.83        73



In [22]:
lgrg.score(x_train,y_train)

0.8538812785388128

# 2 - KNN

In [23]:
from sklearn.neighbors import KNeighborsClassifier
knc = KNeighborsClassifier()
knc.fit(x_train,y_train)

KNeighborsClassifier()

In [24]:
y_pred = knc.predict(x_test)

In [25]:
print(metrics.accuracy_score(y_test,y_pred))
print(metrics.confusion_matrix(y_test,y_pred))
print(metrics.classification_report(y_test,y_pred))

0.863013698630137
[[35  2]
 [ 8 28]]
              precision    recall  f1-score   support

           0       0.81      0.95      0.88        37
           1       0.93      0.78      0.85        36

    accuracy                           0.86        73
   macro avg       0.87      0.86      0.86        73
weighted avg       0.87      0.86      0.86        73



In [26]:
knc.score(x_train,y_train)

0.908675799086758

In [27]:
params = {
    'n_neighbors':[i for i in range(1,30,2)],
    'weights':['uniform','distance'],
}

In [28]:
randomcv_knc = RandomizedSearchCV(knc,param_distributions=params,n_jobs=-1,cv=10,n_iter=100,verbose=True)
randomcv_knc.fit(x_train,y_train)

Fitting 10 folds for each of 30 candidates, totalling 300 fits


C:\Users\LEGION\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:278: UserWarning: The total space of parameters 30 is smaller than n_iter=100. Running 30 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:    0.2s
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:    0.6s finished


RandomizedSearchCV(cv=10, estimator=KNeighborsClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'n_neighbors': [1, 3, 5, 7, 9, 11, 13,
                                                        15, 17, 19, 21, 23, 25,
                                                        27, 29],
                                        'weights': ['uniform', 'distance']},
                   verbose=True)

In [29]:
knc_best = randomcv_knc.best_estimator_

In [30]:
knc_best

KNeighborsClassifier(n_neighbors=7, weights='distance')

In [31]:
knc_clf = KNeighborsClassifier(algorithm='ball_tree', n_neighbors=13, weights='distance')
knc_clf.fit(x_train,y_train)

KNeighborsClassifier(algorithm='ball_tree', n_neighbors=13, weights='distance')

In [32]:
knc_clf.score(x_test,y_test)

0.8493150684931506

In [33]:
knc_clf.score(x_train,y_train)

1.0

# 2 - Decision Tree

In [34]:
from sklearn.tree import DecisionTreeClassifier
dtc = DecisionTreeClassifier()
dtc.fit(x_train,y_train)

DecisionTreeClassifier()

In [35]:
y_p = dtc.predict(x_test)

In [36]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_p))
print(metrics.confusion_matrix(y_test,y_p))
print(metrics.classification_report(y_test,y_p))

0.7671232876712328
[[29  8]
 [ 9 27]]
              precision    recall  f1-score   support

           0       0.76      0.78      0.77        37
           1       0.77      0.75      0.76        36

    accuracy                           0.77        73
   macro avg       0.77      0.77      0.77        73
weighted avg       0.77      0.77      0.77        73



In [37]:
dtc.score(x_train,y_train)

1.0

In [38]:
from sklearn.model_selection import RandomizedSearchCV
params = {
    'max_features' : ['sqrt','auto','log2',None],
    'criterion' : ['gini','entropy'],
    'max_depth':[i for i in range(2,20,1)],
    'splitter':['best','random'],
    'min_samples_split' : [i for i in range(2,50,1)],
    'min_samples_leaf' : [i for i in range(1,50,1)]
}
randomcv_dtc = RandomizedSearchCV(dtc,param_distributions=params,n_jobs=-1,cv=10,n_iter=100,verbose=True)
randomcv_dtc.fit(x_train,y_train)


Fitting 10 folds for each of 100 candidates, totalling 1000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:    0.2s
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed:    1.2s finished


RandomizedSearchCV(cv=10, estimator=DecisionTreeClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [2, 3, 4, 5, 6, 7, 8, 9,
                                                      10, 11, 12, 13, 14, 15,
                                                      16, 17, 18, 19],
                                        'max_features': ['sqrt', 'auto', 'log2',
                                                         None],
                                        'min_samples_leaf': [1, 2, 3, 4, 5, 6,
                                                             7, 8, 9, 10, 11,
                                                             12, 13, 14, 15, 16,
                                                             17, 18, 19, 20, 21,
                                                             22, 23, 24, 25, 26,
                                                  

In [39]:
dtc_best = randomcv_dtc.best_params_


In [40]:
dtc_clf = DecisionTreeClassifier(criterion=dtc_best['criterion'],
                                           min_samples_leaf=dtc_best['min_samples_leaf'],
                                           min_samples_split=dtc_best['min_samples_split'],
                                           max_features=dtc_best['max_features'],
                                splitter=dtc_best['splitter'],max_depth=dtc_best['max_depth'])
dtc_clf.fit(x_train, y_train)



DecisionTreeClassifier(criterion='entropy', max_depth=17, max_features='sqrt',
                       min_samples_split=12)

In [41]:
print("After Hyperparameter Tuning :- ")
print("Training Score :- ",round(dtc_clf.score(x_train,y_train),4))
print("Testing Score :- ",round(dtc_clf.score(x_test,y_test),4))
print()
print("Now the model looks more Generalized !!!")

After Hyperparameter Tuning :- 
Training Score :-  0.9543
Testing Score :-  0.8082

Now the model looks more Generalized !!!


# 3 - Random Forest

In [42]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc.fit(x_train,y_train)

RandomForestClassifier()

In [43]:
y_pre = rfc.predict(x_test)

In [44]:
from sklearn import metrics
print(metrics.accuracy_score(y_test,y_pre))
print(metrics.confusion_matrix(y_test,y_pre))
print(metrics.classification_report(y_test,y_pre))

0.8904109589041096
[[35  2]
 [ 6 30]]
              precision    recall  f1-score   support

           0       0.85      0.95      0.90        37
           1       0.94      0.83      0.88        36

    accuracy                           0.89        73
   macro avg       0.90      0.89      0.89        73
weighted avg       0.90      0.89      0.89        73



In [45]:
rfc.score(x_train,y_train)

1.0

In [46]:
params = {
                'n_estimators': [int(x) for x in np.linspace(start=100,stop=3000,num=30)],
                'criterion': ['gini', 'entropy'],
                'min_samples_leaf': [int(x) for x in range(1, 25, 1)],
                'min_samples_split': [int(x) for x in range(2, 50, 1)],
                'max_features': ['sqrt', 'log2', None],
                'max_depth': [int(x) for x in range(1,31,2)]
            }

In [47]:
rfc_grid = RandomizedSearchCV(estimator=rfc, param_distributions=params, n_iter=100, cv=10, n_jobs=-1, verbose=2,
                                          random_state=101)

In [48]:
rfc_grid.fit(x_train,y_train)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   22.0s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  1.7min
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:  3.7min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  6.3min
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed:  9.7min finished


RandomizedSearchCV(cv=10, estimator=RandomForestClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'criterion': ['gini', 'entropy'],
                                        'max_depth': [1, 3, 5, 7, 9, 11, 13, 15,
                                                      17, 19, 21, 23, 25, 27,
                                                      29],
                                        'max_features': ['sqrt', 'log2', None],
                                        'min_samples_leaf': [1, 2, 3, 4, 5, 6,
                                                             7, 8, 9, 10, 11,
                                                             12, 13, 14, 15, 16,
                                                             17, 18, 19, 20, 21,
                                                             22, 23, 24],
                                        'min_samples_split': [2, 3, 4, 5, 6, 7,
                                                   

In [49]:
rfc_best = rfc_grid.best_params_
print(rfc_best)
            # print(xgbc_best.get_booster().feature_names)
rfc_clf = RandomForestClassifier(criterion=rfc_best['criterion'], n_estimators=rfc_best['n_estimators'],
                                           min_samples_leaf=rfc_best['min_samples_leaf'],
                                           min_samples_split=rfc_best['min_samples_split'],
                                           max_features=rfc_best['max_features'], max_depth=rfc_best['max_depth'])
            
            

{'n_estimators': 2400, 'min_samples_split': 5, 'min_samples_leaf': 4, 'max_features': None, 'max_depth': 29, 'criterion': 'gini'}


In [50]:
rfc_clf.fit(x_train, y_train)

RandomForestClassifier(max_depth=29, max_features=None, min_samples_leaf=4,
                       min_samples_split=5, n_estimators=2400)

In [51]:
print("After Hyperparameter Tuning :- ")
print("Training Score :- ",round(rfc_clf.score(x_train,y_train),4))
print("Testing Score :- ",round(rfc_clf.score(x_test,y_test),4))
print()
print("Now the model looks more Generalized !!!")

After Hyperparameter Tuning :- 
Training Score :-  0.9635
Testing Score :-  0.8493

Now the model looks more Generalized !!!


# 4 - Gradient Boosting Classifier

In [52]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier()
gbc.fit(x_train,y_train)

GradientBoostingClassifier()

In [53]:
y_pr1 = gbc.predict(x_test)

In [54]:
print(metrics.accuracy_score(y_test,y_pr1))
print(metrics.confusion_matrix(y_test,y_pr1))
print(metrics.classification_report(y_test,y_pr1))

0.8767123287671232
[[33  4]
 [ 5 31]]
              precision    recall  f1-score   support

           0       0.87      0.89      0.88        37
           1       0.89      0.86      0.87        36

    accuracy                           0.88        73
   macro avg       0.88      0.88      0.88        73
weighted avg       0.88      0.88      0.88        73



In [55]:
print(gbc.score(x_train,y_train))

1.0


In [56]:
params = {
    'loss':['log_loss','exponential'],
    'learning_rate' :[i for i in np.linspace(0.001,1,50)],
    'n_estimators':[i for i in range(1,301,20)],
    'min_samples_leaf': [int(x) for x in range(1, 25, 1)],
    'min_samples_split': [int(x) for x in range(2, 50, 1)],
    'max_features': ['sqrt', 'log2', None],
    'max_depth': [int(x) for x in range(1,31,2)]
}

In [57]:
gbc_grid = RandomizedSearchCV(estimator=gbc, param_distributions=params, n_iter=100, cv=10, n_jobs=-1, verbose=2,
                                          random_state=101)

In [58]:
gbc_grid.fit(x_train,y_train)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    0.4s
[Parallel(n_jobs=-1)]: Done 848 tasks      | elapsed:    9.6s
[Parallel(n_jobs=-1)]: Done 1000 out of 1000 | elapsed:   13.4s finished


RandomizedSearchCV(cv=10, estimator=GradientBoostingClassifier(), n_iter=100,
                   n_jobs=-1,
                   param_distributions={'learning_rate': [0.001,
                                                          0.021387755102040818,
                                                          0.041775510204081635,
                                                          0.062163265306122456,
                                                          0.08255102040816327,
                                                          0.10293877551020408,
                                                          0.12332653061224491,
                                                          0.1437142857142857,
                                                          0.16410204081632654,
                                                          0.18448979591836737,
                                                          0.20487755102040817,
                                   

In [59]:
gbc_best = gbc_grid.best_params_
print(gbc_best)
gbc_clf = GradientBoostingClassifier(loss=gbc_best['loss'],learning_rate=gbc_best['learning_rate'],
                                    n_estimators=gbc_best['n_estimators'],min_samples_split=gbc_best['min_samples_split'],
                                    min_samples_leaf=gbc_best['min_samples_leaf'],max_features=gbc_best['max_features'],max_depth=gbc_best['max_depth'])
gbc_clf.fit(x_train,y_train)
            
            

{'n_estimators': 201, 'min_samples_split': 44, 'min_samples_leaf': 5, 'max_features': 'sqrt', 'max_depth': 15, 'loss': 'exponential', 'learning_rate': 0.12332653061224491}


GradientBoostingClassifier(learning_rate=0.12332653061224491,
                           loss='exponential', max_depth=15,
                           max_features='sqrt', min_samples_leaf=5,
                           min_samples_split=44, n_estimators=201)

In [60]:
print("Training Score :- ",round(gbc_clf.score(x_train,y_train),4))
print("Testing Score :- ",round(gbc_clf.score(x_test,y_test),4))

Training Score :-  1.0
Testing Score :-  0.9041


# 5 - XGBoost

In [61]:
from xgboost import XGBClassifier
xgbc = XGBClassifier()
xgbc.fit(x_train,y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.300000012, max_delta_step=0, max_depth=6,
              min_child_weight=1, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [62]:
y_pred = xgbc.predict(x_test)

In [63]:
print(metrics.accuracy_score(y_test,y_pred))
print(metrics.confusion_matrix(y_test,y_pred))
print(metrics.classification_report(y_test,y_pred))

0.8356164383561644
[[30  7]
 [ 5 31]]
              precision    recall  f1-score   support

           0       0.86      0.81      0.83        37
           1       0.82      0.86      0.84        36

    accuracy                           0.84        73
   macro avg       0.84      0.84      0.84        73
weighted avg       0.84      0.84      0.84        73



In [64]:
print(xgbc.score(x_train,y_train))

1.0


In [65]:
params = {
                "learning_rate": [float(i) for i in np.linspace(0.001,0.2,20)],
                #"max_depth": [3, 4, 5, 6, 8, 10, 12, 15],
                "min_child_weight": [1, 3, 5, 7],
                "gamma": [float(i) for i in np.linspace(0.1,1,10)],
                "colsample_bytree": [0.2,0.3, 0.4, 0.5, 0.7,0.8,0.9]
            }

In [66]:
xgbc_rndm = RandomizedSearchCV(estimator=xgbc, param_distributions=params, cv=10, n_iter=100, n_jobs=6, verbose=True, random_state=75)
xgbc_rndm.fit(x_train, y_train)

Fitting 10 folds for each of 100 candidates, totalling 1000 fits


[Parallel(n_jobs=6)]: Using backend LokyBackend with 6 concurrent workers.
[Parallel(n_jobs=6)]: Done  40 tasks      | elapsed:    2.1s
[Parallel(n_jobs=6)]: Done 1000 out of 1000 | elapsed:    9.0s finished


RandomizedSearchCV(cv=10,
                   estimator=XGBClassifier(base_score=0.5, booster='gbtree',
                                           colsample_bylevel=1,
                                           colsample_bynode=1,
                                           colsample_bytree=1, gamma=0,
                                           gpu_id=-1, importance_type='gain',
                                           interaction_constraints='',
                                           learning_rate=0.300000012,
                                           max_delta_step=0, max_depth=6,
                                           min_child_weight=1, missing=nan,
                                           monotone_constraints='()',
                                           n_estimators=100, n_jobs=0,
                                           num_p...
                                                          0.04289473684210526,
                                                         

In [67]:
xgbc_best = xgbc_rndm.best_params_
print(xgbc_best)

{'min_child_weight': 5, 'learning_rate': 0.05336842105263158, 'gamma': 0.9, 'colsample_bytree': 0.8}


In [68]:
final_clf = XGBClassifier(learning_rate=xgbc_best['learning_rate'],min_child_weight=xgbc_best['min_child_weight'],gamma=xgbc_best['gamma'],colsample_bytree=xgbc_best['colsample_bytree'])
final_clf.fit(x_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=0.8, gamma=0.9, gpu_id=-1,
              importance_type='gain', interaction_constraints='',
              learning_rate=0.05336842105263158, max_delta_step=0, max_depth=6,
              min_child_weight=5, missing=nan, monotone_constraints='()',
              n_estimators=100, n_jobs=0, num_parallel_tree=1, random_state=0,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, subsample=1,
              tree_method='exact', validate_parameters=1, verbosity=None)

In [69]:
final_clf.score(x_test,y_test)

0.8356164383561644

In [70]:
final_clf.score(x_train,y_train)

0.9497716894977168

# 6 - SVM

In [71]:
from sklearn.svm import SVC
svc = SVC()
svc.fit(x_train,y_train)

SVC()

In [72]:
y_pred = svc.predict(x_test)

In [73]:
print(metrics.accuracy_score(y_test,y_pred))
print(metrics.confusion_matrix(y_test,y_pred))
print(metrics.classification_report(y_test,y_pred))

0.8493150684931506
[[37  0]
 [11 25]]
              precision    recall  f1-score   support

           0       0.77      1.00      0.87        37
           1       1.00      0.69      0.82        36

    accuracy                           0.85        73
   macro avg       0.89      0.85      0.85        73
weighted avg       0.88      0.85      0.85        73



In [74]:
print(svc.score(x_train,y_train))

0.8995433789954338


In [75]:
params = {
                'kernel': ['rbf', 'linear', 'sigmoid', 'poly'],
                'degree': [i for i in range(2, 20, 1)],
                'gamma': ['scale', 'auto'],
                'decision_function_shape': ['ovr', 'ovo']
            }

In [76]:
svc_randomcv = RandomizedSearchCV(estimator=svc, param_distributions=params, n_iter=1000,cv=10, n_jobs=-1, random_state=100, verbose=True)
svc_randomcv.fit(x_train, y_train)

Fitting 10 folds for each of 288 candidates, totalling 2880 fits


C:\Users\LEGION\anaconda3\lib\site-packages\sklearn\model_selection\_search.py:278: UserWarning: The total space of parameters 288 is smaller than n_iter=1000. Running 288 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  56 tasks      | elapsed:    0.1s
[Parallel(n_jobs=-1)]: Done 2160 tasks      | elapsed:    3.1s
[Parallel(n_jobs=-1)]: Done 2880 out of 2880 | elapsed:    4.0s finished


RandomizedSearchCV(cv=10, estimator=SVC(), n_iter=1000, n_jobs=-1,
                   param_distributions={'decision_function_shape': ['ovr',
                                                                    'ovo'],
                                        'degree': [2, 3, 4, 5, 6, 7, 8, 9, 10,
                                                   11, 12, 13, 14, 15, 16, 17,
                                                   18, 19],
                                        'gamma': ['scale', 'auto'],
                                        'kernel': ['rbf', 'linear', 'sigmoid',
                                                   'poly']},
                   random_state=100, verbose=True)

In [77]:
svc_best = svc_randomcv.best_params_
svc_best

{'kernel': 'rbf',
 'gamma': 'scale',
 'degree': 2,
 'decision_function_shape': 'ovr'}

In [78]:
svc_clf = SVC(kernel=svc_best['kernel'], degree=svc_best['degree'], gamma=svc_best['gamma'], decision_function_shape=svc_best['decision_function_shape'])
svc_clf.fit(x_train, y_train)

SVC(degree=2)

In [79]:
svc_clf.score(x_train,y_train)

0.8995433789954338

In [80]:
svc_clf.score(x_test,y_test)

0.8493150684931506